name: Security Checks 

on:
  pull_request:  
    branches:
      - dev
      - staging
      - prod


jobs:
  terraform-security-check:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./deployments
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform fmt
        run: terraform fmt -check
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}
          additional_args: "--minimum-severity HIGH"
          


